### ISSUE TITLE
edr

### ISSUE THREAD

**Issue by sec13b** [Cl0wnK1n9/EDR-bypass#1]
on which EDR has been tested? you've tested it on several EDRs ?

**Comment by Cl0wnK1n9** [comment]
It's no fully bypass any EDR, these program just trying to bypass some hook method that can be use in EDR.

**Comment by sec13b** [comment]
so, to understand , can kill some EDR process ?

**Comment by Cl0wnK1n9** [comment]
Yes base on how edr impliment win api hook. Each edr have diffirence win api hook list and it can be user mode hook or kernel hook mode 
https://github.com/Mr-Un1k0d3r/EDRs

My code just a sample code that create win api hook and way to bypass it so edr won't have information about hooked function which mean no telemetry is sent to edr server to analyze.

**Comment by sec13b** [comment]
i try to compile i get this error : 

Error	MSB3030	Could not copy the file "C:\Users\work\Desktop\Kniget\EDR\EDR-bypass-Cl0wnK1n9\NtWriteVirtualMemoryhook\x64\Release\NtSetInformationProcess.dll" because it was not found.	
Nirvana	
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	2686

**Comment by Cl0wnK1n9** [comment]
You must change the dll path before compile
